#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.java.home=/Users/bruno/Library/Java/JavaVirtualMachines/ms-17.0.20/Contents/Home
# Specify Java toolchain version compatible with Gradle 8.14.3
org.gradle.java.installations.auto-detect=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true